### ISSUE TITLE
Remove special symbol feature in `extern` declarations

### ISSUE THREAD

**Issue by bsdinis** [intel/cryptography-primitives#11]
Adding `:future` to extern declarations in `nasm` causes an error;
Removing it fixes the issue;

The command I ran on the `dispatcher` dir (after building with `cmake`) was:
`grep "extern .*:function$" -l | xargs sed -i -e 's/:function/;:function/'`

**Comment by amatyuko** [comment]
Hi BSDinis,

Could you try the latest NASM [snapshot](https://www.nasm.us/pub/nasm/snapshots/latest/)?
The supported version of NASM for the IPP Crypto is not yet officially released.

Regards,
Andrey

**Comment by bsdinis** [comment]
I compiled and ran NASM 2.14.03rc2, because I couldn't find that version;
However, should the software require an unreleased version of NASM?

(I battled to compile this over the course of the day, and I got the software to compile, are you saying this shouldn't be the case?)

**Comment by amatyuko** [comment]
We are sorry to hear it, but it should not be the case of course (that's why in the README we referenced NASM 2.15 as a minimal required version with the intention that it will be released in future).

The `develop` branch of IPP Crypto sources is somewhat we are working on right now, it might contain new features (sometimes incomplete) that are targeted to the next official release. They work, but as you noticed they might require some additional prerequisites, so you should be careful using this branch.

If you need stable version, please refer to the official release branches (the latest is `ipp-crypto_2020`).

Regards,
Andrey
