### ISSUE TITLE
Incorrect information in documentation

### ISSUE THREAD

**Issue by Krappa322** [intel/cryptography-primitives#6]
Don't know if this is the right place to put it since it's documentation related and not code related but here goes:

pdf and html documentation for ippsGFpInitFixed (page 316) says that primeBitSize is "Size, in bytes, of the odd prime number q (modulus of GF(q)).". Playing around with the function as well as looking at the name however, it seems that this is the size in bits and not bytes.

Also, why is this parameter even needed when using a predefined modulus?

**Comment by skirillo** [comment]
Hi, Doyle3694, thank you for attention to the product.
Regarding to incorrectness of the documentation. Agree, it a bu. It will be fixed soon.
Concerning you question. Take a look at the prototype:
ippsGFpInitFixed,(int primeBitSize, const IppsGFpMethod* pGFpMethod, IppsGFpState* pGFp
To provide correct initialization of context the parameters "primeBitSize" and referenced pGfpMethods methods should be matched each other.
Let me note, we can use pGFpMethod soley, because pGFp context allocated according to "primeBitSIze" without any knowledge what method will be used in the next calls.

**Comment by PavelBerdnikOFF** [comment]
Hi Doyle3694, do you have any questions? Could we close the issue?
